# Builder image
FROM golang:windowsservercore-ltsc2022 as builder

COPY . /neo-go

WORKDIR /neo-go

ARG REPO=repository
ARG VERSION=dev

SHELL ["cmd", "/S", "/C"]
RUN go env -w CGO_ENABLED=0
ENV GOGC=off

RUN go build -trimpath -v -o ./bin/neo-go.exe -ldflags="-X %REPO%/pkg/config.Version=%VERSION%" ./cli/main.go

# Executable image
FROM mcr.microsoft.com/windows/servercore:ltsc2022

ARG VERSION
LABEL version=%VERSION%

WORKDIR /

COPY --from=builder /neo-go/config /config
COPY --from=builder /neo-go/.docker/privnet-entrypoint.ps1 /usr/bin/privnet-entrypoint.ps1
COPY --from=builder /neo-go/bin/neo-go.exe /usr/bin/neo-go.exe
# TODO: Windows Server doesn't have default crt, need to export certs from certmgr
# (see https://stackoverflow.com/questions/26893521/ca-certificate-directory-on-windows).
# COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';", "$ProgressPreference = 'SilentlyContinue';"]

# Check executable version.
RUN /usr/bin/neo-go.exe --version
RUN ls /
RUN ls /usr/bin

#RUN [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; \
# 	Invoke-WebRequest -Uri https://github.com/git-for-windows/git/releases/download/v2.34.0.windows.1/MinGit-2.34.0-64-bit.zip -OutFile 'git.zip'; \
# 	Expand-Archive -Path git.zip -DestinationPath C:\git\.; \
# 	Remove-Item git.zip -Force; \
# 	$env:PATH = 'C:\git\cmd;C:\git\mingw64\bin;C:\git\usr\bin;' + $env:PATH; \
# 	[Environment]::SetEnvironmentVariable('PATH', $env:PATH, [EnvironmentVariableTarget]::Machine); \
# 	git version; \
# 	ls C:\git; \
# 	cp -r C:\git\bin\* /bin/

ENTRYPOINT ["powershell", "-File", "/usr/bin/privnet-entrypoint.ps1"]

#CMD ["powershell", "-Command", "/usr/bin/neo-go.exe", "node", "--config-path", "/config", "-t"]
CMD ["node", "--config-path", "/config", "-t"]

#ENTRYPOINT ["/usr/bin/privnet-entrypoint.sh"]

#CMD ["node", "--config-path", "/config", "--privnet"]
