name: Build

on:
  pull_request:
    branches:
      - master
    types: [opened, synchronize]
    paths-ignore:
      - 'scripts/**'
      - '**/*.md'
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build CLI for Ubuntu and Windows Server Core [default: latest master; examples: v0.92.0, 0a4ff9d3e4a9ab432fd5812eb18c98e03b5a7432]'
        required: false
        default: ''

env:
  GO111MODULE: "on"

jobs:
  build_cli_wsc:
    name: Build CLI (Windows Server Core)
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Restore Go modules from cache
        uses: actions/cache@v2
        with:
          path: /home/runner/go/pkg/mod
          key: deps-${{ hashFiles('go.sum') }}

      - name: Update Go modules
        run: go mod download -json

      - name: Build CLI
        run: make build

      - name: Run VM command
        run: ./bin/neo-go.exe vm

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: neo-go-binaries-wsc
          path: ./bin/neo-go.exe
          if-no-files-found: error