name: Push images to DockerHub

# Controls when the action will run.
on:
  push:
    # Publish `master` as Docker `latest` and `git_revision` images.
    #branches:
    #  - master
  release:
    # Publish released commit as Docker `latest` and `git_revision` images.
    types:
      - published

  # Allows to run this workflow manually from the Actions tab.
  workflow_dispatch:
    inputs:
      ref:
        description: 'Ref to build Docker images for Ubuntu and Windows Server Core [default: latest master; examples: v0.92.0, 0a4ff9d3e4a9ab432fd5812eb18c98e03b5a7432]'
        required: false
        default: ''
      push_image:
        description: 'Push images to DockerHub [default: false; examples: true, false]'
        required: false
        default: 'false'

# Environment variables.
env:
  GO111MODULE: "on"

# A workflow run.
jobs:
  publish_wsc:
    # Ensure test job passes before pushing image.
    #needs: tests_wsc
    name: Publish WindowsServerCore-based image to DockerHub
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref }}
          # Allows to fetch all history for all branches and tags. Need this for proper versioning.
          fetch-depth: 0

      - name: Show docker images
        run: docker images

      - name: Build image
        run: make image-wsc

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push image to registry
        if: ${{ github.event_name == 'release' || (github.event_name == 'workflow_dispatch' && github.event.inputs.push_image == 'true') }}
        run: make image-wsc-push
