name: Update action dependencies
on:
  schedule:
    - cron: '49 13 * * 4'
  workflow_dispatch:

jobs:
  update-deps:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [ "dbft" ]
    steps:
      - uses: actions/checkout@v5
      - name: Clone repository
        run: git clone https://github.com/AnnaShaleva/${{matrix.repo}}.git
      - run: |
          gh api -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2026-03-10" /repos/actions/checkout/releases/latest
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
